// dashboard/src/App.svelte
<script>
  import Sidebar from './lib/Sidebar.svelte';
  import ChatInterface from './lib/ChatInterface.svelte';

  let theme = 'dark';

  function toggleTheme() {
    theme = theme === 'dark' ? 'light' : 'dark';
  }

  $: isDark = theme === 'dark';
</script>

<div class="app" class:dark={isDark} class:light={!isDark}>
  <Sidebar {theme} on:toggleTheme={toggleTheme} />
  
  <main class="content">
    <ChatInterface {theme} />
  </main>

  <!-- Keyboard Shortcut Hint -->
  <div class="shortcut-hint">
    <span><kbd>⌘</kbd> K</span>
    <span class="hint-text">SEARCH ANYWHERE</span>
  </div>
</div>

<style>
  :global(*) {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  :global(body) {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    overflow-x: hidden;
  }

  .app {
    min-height: 100vh;
    width: 100%;
    transition: background-color 0.5s;
  }

  .app.dark {
    background-color: #0a0a0a;
  }

  .app.light {
    background-color: #fafafa;
  }

  .content {
    min-height: 100vh;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 40px 24px;
  }

  .shortcut-hint {
    position: fixed;
    bottom: 24px;
    right: 24px;
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px;
    border-radius: 8px;
    font-size: 11px;
    font-weight: 500;
    letter-spacing: 0.05em;
    transition: all 0.5s;
    z-index: 50;
  }

  .dark .shortcut-hint {
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    color: #6b7280;
  }

  .light .shortcut-hint {
    background: rgba(0, 0, 0, 0.05);
    border: 1px solid rgba(0, 0, 0, 0.05);
    color: #9ca3af;
  }

  .shortcut-hint kbd {
    font-family: inherit;
  }

  .hint-text {
    opacity: 0.4;
  }
</style>

// dashboard/src/app/App.tsx
import React, { useState } from "react";
import { Sidebar } from "./components/Sidebar";
import { ChatInterface } from "./components/ChatInterface";
import { Settings } from "./components/Settings";

export default function App() {
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [showSettings, setShowSettings] = useState(false);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "dark" ? "light" : "dark"));
  };

  const isDark = theme === "dark";

  return (
    <main
      className={`min-h-screen w-full flex items-center justify-center transition-colors duration-500 ${
        isDark ? "bg-[#0a0a0a]" : "bg-[#fafafa]"
      }`}
    >
      <Sidebar 
        theme={theme} 
        toggleTheme={toggleTheme} 
        onOpenSettings={() => setShowSettings(true)}
      />
      
      <div className="w-full flex justify-center py-20 px-6">
        <ChatInterface theme={theme} />
      </div>

      {/* Settings Modal */}
      <Settings 
        isOpen={showSettings} 
        onClose={() => setShowSettings(false)} 
        theme={theme} 
      />

      {/* Keyboard Shortcut Hint */}
      <div className={`fixed bottom-6 right-6 flex items-center gap-2 px-3 py-1.5 rounded-lg border text-[11px] font-medium tracking-wider transition-opacity duration-500 ${
        isDark ? "bg-white/5 border-white/10 text-gray-500" : "bg-black/5 border-black/5 text-gray-400"
      }`}>
        <span className="flex items-center gap-1"><kbd className="font-sans">⌘</kbd> K</span>
        <span className="opacity-40">SEARCH ANYWHERE</span>
      </div>
    </main>
  );
}
